name: publish-to-production

on: workflow_dispatch

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout veesquared.github.io staging
      uses: actions/checkout@v4
      with:
        repository: veesquared/veesquared.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: staging
    - run: | 
        cd staging
        git fetch
        git switch staging
        rm -R .git
        cd ..
    - name: Checkout veesquared.github.io production and deploy production
      uses: actions/checkout@v4
      with:
        repository: veesquared/veesquared.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: production
    - run: | 
        git config --global user.name "github-actions"
        git config --global user.email "12947066+VeeSquared@users.noreply.github.com"
        cd production
        git fetch
        git switch production
        cp -a ../staging/. ./
        touch tmpfile
        git diff --name-only > tmpfile
        minimumsize=0
        tmpfilesize=$(wc -c <"tmpfile")
        if [ $tempfilesize -ge $minimumsize ]; then
        echo tempfilesize = $tempfilesize
        rm tmpfile
        git add .
        git commit -m "Deploy to Production - RunId-"${{ github.run_id }}
        git push 
        fi 
