# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: publish to staging

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    
    - name: Deploy to staging
    - run: git config --global user.name "Vee - Github Actions"
    - run: git config --global user.email "12947066+VeeSquared@users.noreply.github.com"
    - run: gh repo clone VeeSquared/veesquared.github.io
    - run: cd veesquared.github.io
    - run: git fetch
    - run: git switch staging
    - run: git pull
    - run: rm -r *
    - run: cp -a ../build/. ./
    - run: git add .
    - run: git commit -m "Automated Deploy to Staging - RunId-"${{ github.run_id }}
    - run: git push
