name: publish to production

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Clean production
    - run: | 
      rm -r *
    - name: Checkout veesquared.github.io and deploy production
      uses: actions/checkout@v4
      with:
        repository: veesquared/veesquared.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: staging
    - run: | 
        git config --global user.name "github-actions"
        git config --global user.email "12947066+VeeSquared@users.noreply.github.com"
        cd staging
        git pull
        git switch staging
        cp -a /. ../.
        rm -R staging
        git add .
        git commit -m "Automated Deploy to Staging - RunId-"${{ github.run_id }}
        git push  
